/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/courses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Courses */
        get: operations["list_courses_v1_courses_get"];
        put?: never;
        /** Create Course */
        post: operations["create_course_v1_courses_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/courses/{course_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Course */
        get: operations["get_course_v1_courses__course_id__get"];
        put?: never;
        post?: never;
        /** Delete Course */
        delete: operations["delete_course_v1_courses__course_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/courses/{course_id}/metadata": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Course Metadata */
        get: operations["get_course_metadata_v1_courses__course_id__metadata_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Course Metadata */
        patch: operations["update_course_metadata_v1_courses__course_id__metadata_patch"];
        trace?: never;
    };
    "/v1/courses/{course_id}/environment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Course Environment */
        get: operations["get_course_environment_v1_courses__course_id__environment_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch Course Environment */
        patch: operations["patch_course_environment_v1_courses__course_id__environment_patch"];
        trace?: never;
    };
    "/v1/courses/{course_id}/terms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Terms */
        get: operations["get_terms_v1_courses__course_id__terms_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/courses/{course_id}/terms/{term_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Term */
        get: operations["get_term_v1_courses__course_id__terms__term_id__get"];
        put?: never;
        /** Create Term */
        post: operations["create_term_v1_courses__course_id__terms__term_id__post"];
        /** Delete Term */
        delete: operations["delete_term_v1_courses__course_id__terms__term_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/courses/{course_id}/terms/{term_id}/environment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Term Environment */
        get: operations["get_term_environment_v1_courses__course_id__terms__term_id__environment_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch Term Environment */
        patch: operations["patch_term_environment_v1_courses__course_id__terms__term_id__environment_patch"];
        trace?: never;
    };
    "/v1/catalogs/image-catalog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Images */
        get: operations["list_images_v1_catalogs_image_catalog_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/catalogs/resource-tiers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Resources */
        get: operations["list_resources_v1_catalogs_resource_tiers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/catalogs/profile-catalog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Profiles */
        get: operations["list_profiles_v1_catalogs_profile_catalog_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/lms/admins": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Lms Admins */
        get: operations["list_lms_admins_v1_lms_admins_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch Lms Admins */
        patch: operations["patch_lms_admins_v1_lms_admins_patch"];
        trace?: never;
    };
    "/v1/lms/course-creators": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Lms Course Creators */
        get: operations["list_lms_course_creators_v1_lms_course_creators_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch Lms Course Creators */
        patch: operations["patch_lms_course_creators_v1_lms_course_creators_patch"];
        trace?: never;
    };
    "/v1/courses/{course_id}/owners": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Course Owners */
        get: operations["list_course_owners_v1_courses__course_id__owners_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch Course Owners */
        patch: operations["patch_course_owners_v1_courses__course_id__owners_patch"];
        trace?: never;
    };
    "/v1/courses/{course_id}/terms/{term_id}/instructors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Term Instructors */
        get: operations["list_term_instructors_v1_courses__course_id__terms__term_id__instructors_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch Term Instructors */
        patch: operations["patch_term_instructors_v1_courses__course_id__terms__term_id__instructors_patch"];
        trace?: never;
    };
    "/v1/courses/{course_id}/terms/{term_id}/teaching-assistants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Term Teaching Assistants */
        get: operations["list_term_teaching_assistants_v1_courses__course_id__terms__term_id__teaching_assistants_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch Term Teaching Assistants */
        patch: operations["patch_term_teaching_assistants_v1_courses__course_id__terms__term_id__teaching_assistants_patch"];
        trace?: never;
    };
    "/v1/courses/{course_id}/terms/{term_id}/students": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Term Students */
        get: operations["list_term_students_v1_courses__course_id__terms__term_id__students_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch Term Students */
        patch: operations["patch_term_students_v1_courses__course_id__terms__term_id__students_patch"];
        trace?: never;
    };
    "/v1/courses/{course_id}/terms/{term_id}/observers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Term Observers */
        get: operations["list_term_observers_v1_courses__course_id__terms__term_id__observers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch Term Observers */
        patch: operations["patch_term_observers_v1_courses__course_id__terms__term_id__observers_patch"];
        trace?: never;
    };
    "/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Current User */
        get: operations["get_current_user_v1_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CourseCapabilities */
        CourseCapabilities: {
            /** Editmetadata */
            editMetadata: boolean;
            /** Removecourse */
            removeCourse: boolean;
            /** Selectenvironment */
            selectEnvironment: boolean;
            courseOwners: components["schemas"]["MembershipCapabilities"];
            /** Addterm */
            addTerm: boolean;
        };
        /** CourseCollectionCapabilities */
        CourseCollectionCapabilities: {
            /** Createcourse */
            createCourse: boolean;
        };
        /** CourseCollectionResponse */
        CourseCollectionResponse: {
            /** Courses */
            courses: components["schemas"]["CourseSummaryResponse"][];
            capabilities: components["schemas"]["CourseCollectionCapabilities"];
        };
        /** CourseConfig */
        CourseConfig: {
            /** @description Image configuration. */
            image: components["schemas"]["ImageSelection"];
            /**
             * Spawn Role Selections
             * @description Per-spawn role selection configuration.
             */
            spawn_role_selections: {
                [key: string]: components["schemas"]["SpawnRoleSelection"];
            };
            /** @description Metadata information about the course. */
            metadata: components["schemas"]["CourseMetadata"];
            /**
             * Terms
             * @description Per-term configuration overrides.
             */
            terms?: {
                [key: string]: components["schemas"]["TermConfig"];
            };
        };
        /** CourseDetailResponse */
        CourseDetailResponse: {
            metadata: components["schemas"]["CourseMetadata"];
            environment: components["schemas"]["Environment"];
            /** Terms */
            terms: components["schemas"]["TermSummaryResponse"][];
            capabilities: components["schemas"]["CourseCapabilities"];
        };
        /**
         * CourseMetadata
         * @description Metadata information about a course.
         */
        CourseMetadata: {
            /**
             * Course Id
             * @description The id of the course.
             */
            course_id: string;
            /**
             * Course Name
             * @description The full name of the course
             */
            course_name: string;
            /**
             * Description
             * @description An optional text describing the course.
             */
            description?: string | null;
        };
        /**
         * CourseMetadataUpdate
         * @description Request body for updating course metadata.
         */
        CourseMetadataUpdate: {
            /** Course Name */
            course_name?: string | null;
            /** Description */
            description?: string | null;
        };
        /** CourseSummaryResponse */
        CourseSummaryResponse: {
            metadata: components["schemas"]["CourseMetadata"];
            capabilities: components["schemas"]["CourseCapabilities"];
        };
        /**
         * CreateTermRequest
         * @description Request body for creating a term.
         */
        CreateTermRequest: {
            term?: components["schemas"]["TermConfig"] | null;
        };
        /**
         * Environment
         * @description Response body containing the environment configuration of a course or term.
         */
        Environment: {
            image: components["schemas"]["ImageSelection"];
            /**
             * Resources
             * @default {}
             */
            resources: {
                [key: string]: string;
            };
            /**
             * Profiles
             * @default {}
             */
            profiles: {
                [key: string]: string;
            };
        };
        /**
         * EnvironmentUpdate
         * @description Request body for updating the environment configuration of a course or term.
         */
        EnvironmentUpdate: {
            image?: components["schemas"]["ImageSelection"] | null;
            /** Resources */
            resources?: {
                [key: string]: string;
            } | null;
            /** Profiles */
            profiles?: {
                [key: string]: string;
            } | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ImageCatalogResponse */
        ImageCatalogResponse: {
            capabilities: components["schemas"]["InfrastructureCapabilities"];
            catalog: components["schemas"]["ImageFamilyOptions"];
        };
        /**
         * ImageFamilyOption
         * @description An option for a specific image family.
         */
        ImageFamilyOption: {
            /** Display Name */
            display_name: string;
            /** Description */
            description: string;
            /** Default Tag */
            default_tag: string;
            /** Tags */
            tags: {
                [key: string]: components["schemas"]["ImageTagInfo"];
            };
        };
        /**
         * ImageFamilyOptions
         * @description A collection of image family options.
         */
        ImageFamilyOptions: {
            /** Default Family */
            default_family: string;
            /** Families */
            families: {
                [key: string]: components["schemas"]["ImageFamilyOption"];
            };
        };
        /**
         * ImageSelection
         * @description A selection of an image family and an optional tag.
         */
        ImageSelection: {
            /** Family */
            family: string;
            /** Tag */
            tag: string;
        };
        /**
         * ImageTagInfo
         * @description Information about a specific image tag.
         */
        ImageTagInfo: {
            /** Status */
            status: string;
            /** Message */
            message?: string | null;
        };
        /** InfrastructureCapabilities */
        InfrastructureCapabilities: {
            /**
             * Manage
             * @default false
             */
            manage: boolean;
            /**
             * View
             * @default false
             */
            view: boolean;
        };
        /** MembershipCapabilities */
        MembershipCapabilities: {
            /**
             * Add
             * @default false
             */
            add: boolean;
            /**
             * Remove
             * @default false
             */
            remove: boolean;
            /**
             * View
             * @default false
             */
            view: boolean;
        };
        /** MembershipCollectionResponse */
        MembershipCollectionResponse: {
            /** Usernames */
            usernames: string[];
            capabilities: components["schemas"]["MembershipCapabilities"];
        };
        /**
         * MembershipPatch
         * @description Request body for add/remove membership operations.
         */
        MembershipPatch: {
            /**
             * Add
             * @description Usernames to add.
             */
            add?: string[];
            /**
             * Remove
             * @description Usernames to remove.
             */
            remove?: string[];
        };
        /** ProfileCatalogResponse */
        ProfileCatalogResponse: {
            capabilities: components["schemas"]["InfrastructureCapabilities"];
            /** Catalog */
            catalog: {
                [key: string]: components["schemas"]["ProfileOptions"];
            };
        };
        /**
         * ProfileOption
         * @description A profile option for a specific spawn role.
         */
        ProfileOption: {
            /** Display Name */
            display_name: string;
            /** Description */
            description?: string | null;
        };
        /**
         * ProfileOptions
         * @description A collection of profile options for a specific spawn role.
         */
        ProfileOptions: {
            /** Default Profile */
            default_profile: string;
            /** Profiles */
            profiles: {
                [key: string]: components["schemas"]["ProfileOption"];
            };
        };
        /**
         * ResourceTierOption
         * @description A resource tier option for a specific spawn role.
         */
        ResourceTierOption: {
            /** Display Name */
            display_name: string;
            /** Description */
            description: string;
            /** Warning */
            warning?: string | null;
            /** Metadata */
            metadata?: {
                [key: string]: string;
            } | null;
        };
        /**
         * ResourceTierOptions
         * @description A collection of resource tier options for a specific spawn role.
         */
        ResourceTierOptions: {
            /** Default Tier */
            default_tier: string;
            /** Tiers */
            tiers: {
                [key: string]: components["schemas"]["ResourceTierOption"];
            };
        };
        /** ResourceTiersResponse */
        ResourceTiersResponse: {
            capabilities: components["schemas"]["InfrastructureCapabilities"];
            /** Catalog */
            catalog: {
                [key: string]: components["schemas"]["ResourceTierOptions"];
            };
        };
        /**
         * SpawnRole
         * @description Enumeration of spawn roles for the e2x course hub.
         *
         *     Read-only access to the grader environment is not a separate role; it's the
         *     GRADER role spawned with ``SpawnSelection.course_readonly`` set.
         * @enum {string}
         */
        SpawnRole: "student" | "grader";
        /**
         * SpawnRoleSelection
         * @description A selection of spawn options for a specific spawn role
         */
        SpawnRoleSelection: {
            /** Resource Tier Name */
            resource_tier_name: string;
            /** Profile Name */
            profile_name: string;
        };
        /** TermCapabilities */
        TermCapabilities: {
            /** Viewterm */
            viewTerm: boolean;
            /** Removeterm */
            removeTerm: boolean;
            /** Selectenvironment */
            selectEnvironment: boolean;
            membership: components["schemas"]["TermMembershipCapabilities"];
        };
        /**
         * TermConfig
         * @description Configuration for a specific term.
         */
        TermConfig: {
            /** @description Image configuration. */
            image: components["schemas"]["ImageSelection"];
            /**
             * Spawn Role Selections
             * @description Per-spawn role selection configuration.
             */
            spawn_role_selections: {
                [key: string]: components["schemas"]["SpawnRoleSelection"];
            };
        };
        /** TermDetailResponse */
        TermDetailResponse: {
            /** Course Id */
            course_id: string;
            /** Term Id */
            term_id: string;
            environment: components["schemas"]["Environment"];
            capabilities: components["schemas"]["TermCapabilities"];
        };
        /** TermMembershipCapabilities */
        TermMembershipCapabilities: {
            instructors: components["schemas"]["MembershipCapabilities"];
            teachingAssistants: components["schemas"]["MembershipCapabilities"];
            students: components["schemas"]["MembershipCapabilities"];
            observers: components["schemas"]["MembershipCapabilities"];
        };
        /** TermSummaryCapabilities */
        TermSummaryCapabilities: {
            /** Viewterm */
            viewTerm: boolean;
            /** Removeterm */
            removeTerm: boolean;
        };
        /** TermSummaryResponse */
        TermSummaryResponse: {
            /** Course Id */
            course_id: string;
            /** Term Id */
            term_id: string;
            capabilities: components["schemas"]["TermSummaryCapabilities"];
        };
        /** UserResponse */
        UserResponse: {
            /** Username */
            username: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_courses_v1_courses_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CourseCollectionResponse"];
                };
            };
        };
    };
    create_course_v1_courses_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CourseConfig"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CourseMetadata"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_course_v1_courses__course_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                course_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CourseDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_course_v1_courses__course_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                course_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_course_metadata_v1_courses__course_id__metadata_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                course_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CourseMetadata"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_course_metadata_v1_courses__course_id__metadata_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                course_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CourseMetadataUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CourseMetadata"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_course_environment_v1_courses__course_id__environment_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                course_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Environment"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_course_environment_v1_courses__course_id__environment_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                course_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EnvironmentUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Environment"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_terms_v1_courses__course_id__terms_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                course_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TermSummaryResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_term_v1_courses__course_id__terms__term_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                course_id: string;
                term_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TermDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_term_v1_courses__course_id__terms__term_id__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                course_id: string;
                term_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["CreateTermRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TermDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_term_v1_courses__course_id__terms__term_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                course_id: string;
                term_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_term_environment_v1_courses__course_id__terms__term_id__environment_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                course_id: string;
                term_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Environment"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_term_environment_v1_courses__course_id__terms__term_id__environment_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                course_id: string;
                term_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EnvironmentUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Environment"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_images_v1_catalogs_image_catalog_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImageCatalogResponse"];
                };
            };
        };
    };
    list_resources_v1_catalogs_resource_tiers_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResourceTiersResponse"];
                };
            };
        };
    };
    list_profiles_v1_catalogs_profile_catalog_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileCatalogResponse"];
                };
            };
        };
    };
    list_lms_admins_v1_lms_admins_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MembershipCollectionResponse"];
                };
            };
        };
    };
    patch_lms_admins_v1_lms_admins_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MembershipPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_lms_course_creators_v1_lms_course_creators_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MembershipCollectionResponse"];
                };
            };
        };
    };
    patch_lms_course_creators_v1_lms_course_creators_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MembershipPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_course_owners_v1_courses__course_id__owners_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                course_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MembershipCollectionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_course_owners_v1_courses__course_id__owners_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                course_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MembershipPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_term_instructors_v1_courses__course_id__terms__term_id__instructors_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                course_id: string;
                term_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MembershipCollectionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_term_instructors_v1_courses__course_id__terms__term_id__instructors_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                course_id: string;
                term_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MembershipPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_term_teaching_assistants_v1_courses__course_id__terms__term_id__teaching_assistants_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                course_id: string;
                term_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MembershipCollectionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_term_teaching_assistants_v1_courses__course_id__terms__term_id__teaching_assistants_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                course_id: string;
                term_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MembershipPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_term_students_v1_courses__course_id__terms__term_id__students_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                course_id: string;
                term_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MembershipCollectionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_term_students_v1_courses__course_id__terms__term_id__students_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                course_id: string;
                term_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MembershipPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_term_observers_v1_courses__course_id__terms__term_id__observers_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                course_id: string;
                term_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MembershipCollectionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_term_observers_v1_courses__course_id__terms__term_id__observers_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                course_id: string;
                term_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MembershipPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_current_user_v1_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
        };
    };
}
